## LANGUAGE
defaultContentLanguage: fr
languageCode: fr

## ADVANCED
build:
  writeStats: true
enableRobotsTXT: true
imaging:
  quality: 90
markup:
  tableOfContents:
    ordered: true
pagination.pagerSize: 20
removePathAccents: true
disableHugoGeneratorInject: true
