[build]
  command = "yarn build"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.114.0"
  GO_VERSION = "1.20.5"

[context.branch-deploy.environment]
  HUGO_ENV = "staging"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
