[build]
  command = "yarn build"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.120.0"
  GO_VERSION = "1.21.3"

[context.branch-deploy.environment]
  HUGO_ENV = "staging"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
